/**
 * Curated seed records for the negotiation knowledge base (IN-4, BB-227,
 * docs/18 §5). ~25 records: real scholarship only — open-access papers,
 * licensed material (citation + curated summary; we never host full
 * text), bibliographic references, and our own curated summaries.
 * No indiscriminate book ingestion; every item carries provenance
 * (authors, year, publication, citation). DOIs are included only where
 * confidently known, never invented.
 *
 * All seeds ship review_status DRAFT, reviewed_by null — human/founder
 * review is required before IN-5 retrieval cites them.
 */

import type { KnowledgeRecord } from './knowledge';

/** Explicit seed timestamp (2026-09-24T00:00:00Z) — data, not a clock read. */
const SEED_CREATED_AT = 1744243200000;

export const KNOWLEDGE_SEEDS: readonly KnowledgeRecord[] = [
  {
    id: 'kb-galinsky-first-offers',
    title: 'First offers as anchors: the role of perspective-taking and negotiator focus',
    summary:
      'Laboratory experiments showing that first offers strongly anchor final outcomes, and that a negotiator\'s focus (own target vs counterpart\'s BATNA) changes both the first offer and the result.',
    ontology_tags: ['FIRST_OFFERS', 'ANCHORING'],
    claim: 'First offers anchor negotiation outcomes — the number that opens the exchange pulls the settlement toward it.',
    practical_implication: 'Prepare your opening deliberately: it shapes the rest of the exchange. When facing an anchor, shift focus to the counterpart\'s alternatives rather than counter-anchoring from their number.',
    conditions: 'Anchoring is strongest when the counterpart lacks clear information about the value at stake and accepts the opening number as a plausible reference point.',
    limitations: 'Laboratory experiments with student dyads and Western samples; single-issue monetary games may amplify anchor effects relative to repeated, multi-issue, relationship-based negotiation.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Adam D. Galinsky', 'Thomas Mussweiler'],
    year: 2001,
    publication: 'Journal of Personality and Social Psychology, 81(4), 657–669',
    doi_url: 'https://doi.org/10.1037/0022-3514.81.4.657',
    citation_text: 'Galinsky, A. D., & Mussweiler, T. (2001). First offers as anchors: The role of perspective-taking and negotiator focus. Journal of Personality and Social Psychology, 81(4), 657–669.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-never-open-first',
    title: '"Never make the first offer" — practitioner heuristic',
    summary:
      'A common practitioner rule of thumb: whoever opens first reveals information and hands the other side an anchor, so wait and let the counterparty commit to a number first.',
    ontology_tags: ['FIRST_OFFERS', 'ANCHORING'],
    claim: 'Some practitioners advise never making the first offer, on the grounds that opening first concedes information and gives the counterparty the anchor.',
    practical_implication: 'In some competitive, information-rich settings, letting the other side open first is a live option — but treat the rule as context-dependent, not universal.',
    conditions: 'Most relevant when you know little about the counterpart\'s constraints and cannot prepare a well-placed anchor of your own.',
    limitations: 'Contested: anchoring research (see kb-galinsky-first-offers) shows first offers pull outcomes toward the opener, which can favor a well-prepared opener. No systematic empirical support for the rule as a universal strategy.',
    evidence_level: 'D',
    source_type: 'CURATED_SUMMARY',
    authors: ['Common practitioner literature'],
    year: 2026,
    publication: 'Curated summary of common practitioner advice (this knowledge base)',
    doi_url: null,
    citation_text: 'Curated summary of recurring practitioner advice; contrasted with Galinsky & Mussweiler (2001), JPSP 81(4), 657–669.',
    license_access: { license: null, access: 'OPEN' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-thompson-hastie-fixed-pie',
    title: 'Social perception in negotiation',
    summary:
      'Experiments showing that negotiators routinely assume a fixed pie and therefore fail to detect issues where both sides want the same thing, leaving joint value on the table.',
    ontology_tags: ['FIXED_PIE', 'VALUE_CREATION'],
    claim: 'Negotiators commonly enter an exchange assuming a fixed pie, and this assumption persists even after information that could reveal compatible interests is available.',
    practical_implication: 'Actively test for compatibility before assuming every issue is win-lose; ask about priorities rather than positions.',
    conditions: 'The bias is strongest early in an exchange and when parties do not exchange priority information.',
    limitations: 'Student-participant laboratory games; real negotiations with long histories or professional stakes may show different baseline awareness.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Leigh Thompson', 'Reid Hastie'],
    year: 1990,
    publication: 'Organizational Behavior and Human Decision Processes, 47(1), 98–123',
    doi_url: null,
    citation_text: 'Thompson, L., & Hastie, R. (1990). Social perception in negotiation. Organizational Behavior and Human Decision Processes, 47(1), 98–123.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-bazerman-integrative-market',
    title: 'Integrative bargaining in a competitive market',
    summary:
      'A market experiment in which buyers and sellers operating under fixed-sum assumptions settled less efficiently than the integrative structure of the exchange allowed.',
    ontology_tags: ['FIXED_PIE', 'VALUE_CREATION'],
    claim: 'Fixed-pie expectations lead negotiators to settle at outcomes below the value the exchange could support.',
    practical_implication: 'Revisit "either-or" assumptions during a negotiation: the structure may hold value both sides can claim together.',
    conditions: 'Applies to exchanges with multiple issues or differences in valuation across parties.',
    limitations: 'Single experimental market; outcomes depend on the information structure and incentives of the game.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Max H. Bazerman', 'Thomas Magliozzi', 'Margaret A. Neale'],
    year: 1985,
    publication: 'Organizational Behavior and Human Decision Processes, 35(3), 294–313',
    doi_url: null,
    citation_text: 'Bazerman, M. H., Magliozzi, T., & Neale, M. A. (1985). Integrative bargaining in a competitive market. Organizational Behavior and Human Decision Processes, 35(3), 294–313.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-vankleef-anger',
    title: 'The interpersonal effects of anger and happiness in negotiations',
    summary:
      'Experiments showing that a counterpart\'s anger elicits larger concessions when the negotiator has weak alternatives, because anger signals a tough limit.',
    ontology_tags: ['EMOTION', 'POWER'],
    claim: 'An angry counterpart tends to extract larger concessions from negotiators who have weak alternatives to the deal.',
    practical_implication: 'Read the other side\'s emotional signals as information about their limits — and know your own alternatives before deciding how much weight to give them.',
    conditions: 'The concession effect holds when the negotiator\'s alternatives are weak and the anger is perceived as genuine.',
    limitations: 'Laboratory settings with scripted emotions; does not address long-term relationship costs of expressing anger, which can be negative.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Gerben A. Van Kleef', 'Carsten K. W. De Dreu', 'Antony S. R. Manstead'],
    year: 2004,
    publication: 'Journal of Personality and Social Psychology, 86(1), 57–76',
    doi_url: 'https://doi.org/10.1037/0022-3514.86.1.57',
    citation_text: 'Van Kleef, G. A., De Dreu, C. K. W., & Manstead, A. S. R. (2004). The interpersonal effects of anger and happiness in negotiations. Journal of Personality and Social Psychology, 86(1), 57–76.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-curhan-subjective-value',
    title: 'What do people value when they negotiate? Mapping the domain of subjective value',
    summary:
      'Developed and validated a Subjective Value Inventory: negotiators care about instrumental outcome, self, process, and relationship — not just the number.',
    ontology_tags: ['EMOTION', 'FACE', 'TRUST'],
    claim: 'Negotiators evaluate deals on four subjective factors — instrumental outcome, feelings about the self, the process, and the relationship — and these predict future behavior beyond economic outcomes.',
    practical_implication: 'A deal that maximizes your number but leaves the counterpart feeling disrespected can cost you later; process and relationship are part of the result.',
    conditions: 'Subjective value matters most when the parties expect to interact again or when reputation is at stake.',
    limitations: 'Survey and scenario methods; self-reported value, not behavioral outcomes in all studies.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Jared R. Curhan', 'Hillary Anger Elfenbein', 'Heng Xu'],
    year: 2006,
    publication: 'Journal of Personality and Social Psychology, 91(3), 493–512',
    doi_url: 'https://doi.org/10.1037/0022-3514.91.3.493',
    citation_text: 'Curhan, J. R., Elfenbein, H. A., & Xu, H. (2006). What do people value when they negotiate? Mapping the domain of subjective value in negotiation. Journal of Personality and Social Psychology, 91(3), 493–512.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-stuhlmacher-time-pressure',
    title: 'The impact of time pressure in negotiation: a meta-analysis',
    summary:
      'A meta-analysis of negotiation studies examining how time pressure changes negotiator behavior and outcomes.',
    ontology_tags: ['TIME_PRESSURE', 'DEADLINES'],
    claim: 'Across negotiation studies, time pressure is associated with lower individual outcomes and a greater tendency toward concession behavior.',
    practical_implication: 'Time pressure is a real lever: whoever owns the deadline owns part of the exchange. Manage your own clock (and the other side\'s perception of yours).',
    conditions: 'Effect sizes vary with how pressure is induced and whether both or one party is under pressure.',
    limitations: 'Meta-analysis of heterogeneous laboratory studies; field evidence on real deadlines is thinner.',
    evidence_level: 'A',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Alice F. Stuhlmacher', 'Treena L. Gillespie', 'Matthew V. Champagne'],
    year: 1998,
    publication: 'International Journal of Conflict Management, 9(2), 97–123',
    doi_url: null,
    citation_text: 'Stuhlmacher, A. F., Gillespie, T. L., & Champagne, M. V. (1998). The impact of time pressure in negotiation: A meta-analysis. International Journal of Conflict Management, 9(2), 97–123.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-zetik-goals',
    title: 'Goal setting and negotiation performance: a meta-analysis',
    summary:
      'Meta-analysis of goal-setting research in negotiation: specific, ambitious targets improve results.',
    ontology_tags: ['ASPIRATION_TARGET', 'PLANNING'],
    claim: 'Negotiators with specific, ambitious goals reach higher outcomes than those with easy, vague, or no goals.',
    practical_implication: 'Set a specific target before you sit down — aspiration is one of the strongest controllable inputs to a negotiation.',
    conditions: 'Goal effects assume commitment to the goal and the ability to measure progress against it.',
    limitations: 'Laboratory dominance; ambitious goals in real stakes may also raise the risk of deadlock if unmanaged.',
    evidence_level: 'A',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Deborah A. Zetik', 'Alice F. Stuhlmacher'],
    year: 2002,
    publication: 'Group Dynamics: Theory, Research, and Practice, 6(2), 135–146',
    doi_url: null,
    citation_text: 'Zetik, D. A., & Stuhlmacher, A. F. (2002). Goal setting and negotiation performance: A meta-analysis. Group Dynamics: Theory, Research, and Practice, 6(2), 135–146.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-kahneman-loss-aversion',
    title: 'Prospect theory: an analysis of decision under risk',
    summary:
      'Foundational decision theory: people evaluate outcomes relative to a reference point and weight losses more heavily than equivalent gains.',
    ontology_tags: ['LOSS_AVERSION', 'FRAMING'],
    claim: 'Losses loom larger than gains of equal size — choices are evaluated against a reference point, not in absolute terms.',
    practical_implication: 'Expect the other side to overreact to what they might lose; frame proposals around what they keep rather than what they give up.',
    conditions: 'Applies to risky and framed choices generally; the negotiation literature applies it to concession framing and walk-away decisions.',
    limitations: 'Foundational theory, not negotiation data; magnitude of loss aversion varies across contexts, stakes, and populations.',
    evidence_level: 'A',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Daniel Kahneman', 'Amos Tversky'],
    year: 1979,
    publication: 'Econometrica, 47(2), 263–291',
    doi_url: 'https://doi.org/10.2307/1914185',
    citation_text: 'Kahneman, D., & Tversky, A. (1979). Prospect theory: An analysis of decision under risk. Econometrica, 47(2), 263–291.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-ames-mason-tandem',
    title: 'Tandem anchoring: informational and politeness effects of range offers',
    summary:
      'Experiments on range offers ("I would take 500–550"): ranges anchor the counterpart while appearing more polite than a single aggressive number.',
    ontology_tags: ['FIRST_OFFERS', 'ANCHORING', 'FACE'],
    claim: 'Range offers anchor counterparts toward the favorable end of the range while being read as more polite than a single demanding number.',
    practical_implication: 'When you must open with an ambitious position, a range can soften the ask without giving up the anchor.',
    conditions: 'Effects depend on the range width and on counterpart information; a wide range can invite anchoring at its favorable end.',
    limitations: 'Laboratory exchanges; politeness perceptions may differ across cultures and stakes.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Daniel R. Ames', 'Malia F. Mason'],
    year: 2015,
    publication: 'Journal of Personality and Social Psychology, 108(2), 254–274',
    doi_url: null,
    citation_text: 'Ames, D. R., & Mason, M. F. (2015). Tandem anchoring: Informational and politeness effects of range offers in social exchange. Journal of Personality and Social Psychology, 108(2), 254–274.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-pruitt-lewis-integrative',
    title: 'Development of integrative solutions in bilateral negotiation',
    summary:
      'Classic experiments on what makes integrative agreements happen: open, problem-solving exchange of information about values and priorities.',
    ontology_tags: ['VALUE_CREATION', 'INFORMATION_DISCLOSURE'],
    claim: 'A problem-solving orientation, with open exchange of information about priorities, produces more integrative (value-creating) agreements.',
    practical_implication: 'To create value, exchange information about what you value differently — selectively and with trust built incrementally.',
    conditions: 'Information exchange helps most when parties have genuinely different priorities across issues.',
    limitations: 'Laboratory dyads; in competitive settings, disclosure carries exploitation risk (see the negotiator\'s dilemma, kb-lax-sebenius).',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Dean G. Pruitt', 'Steven A. Lewis'],
    year: 1975,
    publication: 'Journal of Personality and Social Psychology, 31(4), 621–633',
    doi_url: null,
    citation_text: 'Pruitt, D. G., & Lewis, S. A. (1975). Development of integrative solutions in bilateral negotiation. Journal of Personality and Social Psychology, 31(4), 621–633.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-dedreu-pressure-mind',
    title: 'Time pressure and closing of the mind in negotiation',
    summary:
      'Experiments on how time pressure changes information processing in negotiation: more heuristic, less deliberate.',
    ontology_tags: ['TIME_PRESSURE'],
    claim: 'Under time pressure, negotiators rely more on heuristic processing and adjust less to new information.',
    practical_implication: 'Do not assume calm deliberation in the endgame: last-minute decisions run on shortcuts. Bank time early.',
    conditions: 'Heuristic shift is strongest when pressure arrives late in the exchange.',
    limitations: 'Laboratory time limits; field deadlines involve other features (authority, coordination costs).',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Carsten K. W. De Dreu'],
    year: 2003,
    publication: 'Organizational Behavior and Human Decision Processes, 91(2), 280–295',
    doi_url: null,
    citation_text: 'De Dreu, C. K. W. (2003). Time pressure and closing of the mind in negotiation. Organizational Behavior and Human Decision Processes, 91(2), 280–295.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-ross-reactive-devaluation',
    title: 'Barriers to conflict resolution',
    summary:
      'Identifies psychological barriers to agreement, including reactive devaluation: offers are valued less simply because they come from the other side.',
    ontology_tags: ['REACTIVE_DEVALUATION', 'TRUST'],
    claim: 'Proposals are evaluated less favorably when they come from an opposing party than when identical proposals come from a neutral or own side.',
    practical_implication: 'When the other side\'s offer looks insulting, test whether the content or the source is driving your reaction.',
    conditions: 'Strongest in entrenched, low-trust relationships.',
    limitations: 'Conceptual synthesis plus illustrative evidence; magnitude varies with conflict intensity.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Lee Ross', 'Constance Stillinger'],
    year: 1991,
    publication: 'Negotiation Journal, 7(4), 389–404',
    doi_url: null,
    citation_text: 'Ross, L., & Stillinger, C. (1991). Barriers to conflict resolution. Negotiation Journal, 7(4), 389–404.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-malhotra-psychological-influence',
    title: 'Psychological influence in negotiation: an introduction long overdue',
    summary:
      'Review of psychological influence tactics negotiators actually use — framing, anchoring, reciprocity-based pressure — that standard economic models miss.',
    ontology_tags: ['FRAMING', 'ANCHORING', 'RECIPROCITY'],
    claim: 'Negotiators routinely exert influence through psychological mechanisms (framing, anchoring, exploiting reciprocity) beyond the exchange of prices.',
    practical_implication: 'Expect influence attempts that are not arguments; recognize them and respond on the merits of your own analysis.',
    conditions: 'Applies to all negotiations; tactics vary in legitimacy and effect.',
    limitations: 'A review, not primary data; classifications of tactics remain debated.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Deepak Malhotra', 'Max H. Bazerman'],
    year: 2008,
    publication: 'Journal of Management, 34(3), 509–531',
    doi_url: null,
    citation_text: 'Malhotra, D., & Bazerman, M. H. (2008). Psychological influence in negotiation: An introduction long overdue. Journal of Management, 34(3), 509–531.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-gunia-trust-culture',
    title: 'Paying a price: culture, trust, and negotiation consequences',
    summary:
      'Cross-cultural negotiation study: trust in the counterparty mediated the relationship between cultural background and negotiated outcomes.',
    ontology_tags: ['TRUST', 'CULTURE'],
    claim: 'In a cross-cultural negotiation study, negotiators\' trust in their counterpart mediated differences in negotiated outcomes between cultural groups.',
    practical_implication: 'Where cultural distance exists, invest early in trust-building moves before pushing for value.',
    conditions: 'Findings come from a specific U.S.–India comparison and may not generalize to other cultural pairings.',
    limitations: 'Single comparison context; culture is measured at group level, with wide within-group variance.',
    evidence_level: 'B',
    source_type: 'LICENSED_MATERIAL',
    authors: ['Brian C. Gunia', 'Jeanne M. Brett', 'Amit K. Nandkeolyar', 'Dishan Kamdar'],
    year: 2011,
    publication: 'Journal of Applied Psychology, 96(4), 774–789',
    doi_url: null,
    citation_text: 'Gunia, B. C., Brett, J. M., Nandkeolyar, A. K., & Kamdar, D. (2011). Paying a price: Culture, trust, and negotiation consequences. Journal of Applied Psychology, 96(4), 774–789.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-fisher-getting-to-yes',
    title: 'Getting to Yes: Negotiating agreement without giving in',
    summary:
      'The principled-negotiation framework: separate the people from the problem, focus on interests not positions, invent options before deciding, and insist on objective criteria — with BATNA as the fallback standard.',
    ontology_tags: ['INTERESTS', 'BATNA', 'PLANNING'],
    claim: 'A widely used negotiation framework recommends negotiating on interests and objective criteria, anchored by a prepared best alternative (BATNA), rather than exchanging positional demands.',
    practical_implication: 'Prepare your BATNA before the match — it is the floor under every offer you make or consider.',
    conditions: 'The framework is designed for two-party negotiation where both sides prefer agreement to its absence; adversarial or single-shot distributive settings use it differently.',
    limitations: 'Practitioner framework rather than controlled evidence; later research qualifies parts of it (e.g., opening anchors can matter despite principled negotiation\'s skepticism of positions).',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['Roger Fisher', 'William Ury'],
    year: 1981,
    publication: 'Houghton Mifflin (book)',
    doi_url: null,
    citation_text: 'Fisher, R., & Ury, W. (1981). Getting to Yes: Negotiating agreement without giving in. Houghton Mifflin.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-raiffa-art-science',
    title: 'The Art and Science of Negotiation',
    summary:
      'Analytical foundation of negotiation: the cooperative (value-creating) and competitive (value-claiming) sides of the same exchange, and how to prepare against both.',
    ontology_tags: ['VALUE_CREATION', 'VALUE_CAPTURE'],
    claim: 'A widely used negotiation framework recommends treating negotiation as having both a cooperative, value-creating side and a competitive, value-claiming side that must be managed together.',
    practical_implication: 'Preparation covers both questions: how can the pie grow, and how will it be split.',
    conditions: 'The dual structure is cleanest in two-party, mixed-motive settings.',
    limitations: 'Prescriptive analytics rather than empirical findings; assumes a degree of rationality and information access that real play rarely offers fully.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['Howard Raiffa'],
    year: 1982,
    publication: 'Harvard University Press (book)',
    doi_url: null,
    citation_text: 'Raiffa, H. (1982). The Art and Science of Negotiation. Harvard University Press.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-lax-sebenius-negotiators-dilemma',
    title: 'The Manager as Negotiator',
    summary:
      'Frames the negotiator\'s dilemma: moves that create value also expose one to claiming, so every cooperative move carries a competitive risk.',
    ontology_tags: ['VALUE_CREATION', 'VALUE_CAPTURE', 'TRUST'],
    claim: 'A widely used negotiation framework recommends managing the negotiator\'s dilemma — value-creating moves can be exploited, so creation and claiming tactics must be balanced deliberately.',
    practical_implication: 'Build value-creating moves to be robust: disclose selectively, trade on differences, and protect your core positions.',
    conditions: 'The dilemma is sharpest with partial information and repeat interaction absent.',
    limitations: 'Analytic framework; the optimal balance varies by relationship, stakes, and information structure.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['David A. Lax', 'James K. Sebenius'],
    year: 1986,
    publication: 'Free Press (book)',
    doi_url: null,
    citation_text: 'Lax, D. A., & Sebenius, J. K. (1986). The Manager as Negotiator. Free Press.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-thompson-mind-heart',
    title: 'The Mind and Heart of the Negotiator',
    summary:
      'Practitioner-research synthesis of negotiation strategy, including logrolling: trading across issues the parties value differently to create joint value.',
    ontology_tags: ['MULTI_ISSUE_TRADING', 'LOGROLLING'],
    claim: 'A widely used negotiation framework recommends logrolling — conceding issues you value less for gains on issues you value more, using differences in priorities to create value.',
    practical_implication: 'In multi-issue exchanges, rank your issues before you sit down; concession packages beat single-issue haggling.',
    conditions: 'Requires multiple issues with asymmetric valuations; weaker in single-issue settings (like most Bounty Bay matches today).',
    limitations: 'Synthesis of practitioner experience and research; single-issue settings limit applicability.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['Leigh Thompson'],
    year: 2000,
    publication: 'Prentice Hall (book)',
    doi_url: null,
    citation_text: 'Thompson, L. (2000). The Mind and Heart of the Negotiator. Prentice Hall.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-ury-getting-past-no',
    title: 'Getting Past No: Negotiating in difficult situations',
    summary:
      'Framework for breaking through resistance and impasse: don\'t react, disarm the opponent, reframe the problem, and make the other side an easy way to say yes.',
    ontology_tags: ['IMPASSE', 'LISTENING'],
    claim: 'A widely used negotiation framework recommends a sequence for impasse: control your own reaction, acknowledge the other side\'s position, reframe toward interests, and offer an easy path to agreement.',
    practical_implication: 'When a negotiation stalls, step back before counter-attacking; an acknowledgment can restart movement where a demand cannot.',
    conditions: 'Designed for stalled negotiations where some willingness to continue exists.',
    limitations: 'Practitioner framework; effectiveness in pure distributive settings is unproven.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['William Ury'],
    year: 1991,
    publication: 'Bantam Books (book)',
    doi_url: null,
    citation_text: 'Ury, W. (1991). Getting Past No: Negotiating in difficult situations. Bantam Books.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-malhotra-negotiation-genius',
    title: 'Negotiation Genius',
    summary:
      'Practitioner-research synthesis built around investigative negotiation: systematically investigate the counterpart\'s interests, constraints, and alternatives before and during the negotiation.',
    ontology_tags: ['INFORMATION_GATHERING', 'VALUE_CREATION'],
    claim: 'A widely used negotiation framework recommends investigative negotiation — asking questions and gathering information about the counterpart\'s constraints before choosing tactics.',
    practical_implication: 'Questions beat assumptions: a single piece of constraint information can be worth more than any concession.',
    conditions: 'Information-gathering value depends on the counterpart\'s willingness to disclose (see disclosure risk, kb-pruitt-lewis-integrative).',
    limitations: 'Practitioner synthesis; the causal role of investigation is plausible but not isolated experimentally.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['Deepak Malhotra', 'Max H. Bazerman'],
    year: 2007,
    publication: 'Bantam Books (book)',
    doi_url: null,
    citation_text: 'Malhotra, D., & Bazerman, M. H. (2007). Negotiation Genius. Bantam Books.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-walton-mckersie',
    title: 'A Behavioral Theory of Labor Negotiations',
    summary:
      'Classic distinction between distributive bargaining (splitting a fixed pie) and integrative bargaining (finding joint gains), still the organizing frame for negotiation analysis.',
    ontology_tags: ['VALUE_CAPTURE', 'VALUE_CREATION'],
    claim: 'A widely used negotiation framework recommends distinguishing distributive from integrative bargaining processes and managing them with different tactics.',
    practical_implication: 'Diagnose which process you are in before choosing tactics — the same move is rational in one and wasteful in the other.',
    conditions: 'The distinction is analytic; real negotiations mix both processes.',
    limitations: 'Framework from labor-relations context; single-issue exchanges are purely distributive, so integrative tactics cannot apply.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['Richard E. Walton', 'Robert B. McKersie'],
    year: 1965,
    publication: 'McGraw-Hill (book)',
    doi_url: null,
    citation_text: 'Walton, R. E., & McKersie, R. B. (1965). A Behavioral Theory of Labor Negotiations. McGraw-Hill.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-sebenius-negotiation-analysis',
    title: 'Negotiation analysis: a characterization and review',
    summary:
      'Review characterizing negotiation analysis: value comes not only from claiming within a fixed game but from changing the game — the issue set, the sequence, and the parties\' BATNAs.',
    ontology_tags: ['BATNA', 'VALUE_CREATION', 'INFORMATION_GATHERING'],
    claim: 'A widely used negotiation framework recommends examining the game itself — the issue set, sequencing, and alternatives on both sides — as the largest source of value, beyond in-game tactics.',
    practical_implication: 'Before conceding on a bad issue, ask whether the issue list, order, or alternatives themselves can be changed.',
    conditions: 'Game-changing moves require leverage or information the other side lacks.',
    limitations: 'Review and synthesis; game-changing tactics can violate fairness norms in some settings.',
    evidence_level: 'C',
    source_type: 'LICENSED_MATERIAL',
    authors: ['James K. Sebenius'],
    year: 1992,
    publication: 'Management Science, 38(1), 18–38',
    doi_url: null,
    citation_text: 'Sebenius, J. K. (1992). Negotiation analysis: A characterization and review. Management Science, 38(1), 18–38.',
    license_access: { license: null, access: 'SUBSCRIPTION' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-babcock-women-dont-ask',
    title: 'Women Don\'t Ask: Negotiation and the gender divide',
    summary:
      'Documents a descriptive gap in negotiation initiation: in the studied samples, women initiated negotiations less often than men, leaving compensation and opportunity unclaimed.',
    ontology_tags: ['AMBITION'],
    claim: 'A widely used negotiation framework recommends recognizing that initiation itself is negotiated — in the studied samples, many people (women in particular) did not open negotiations and left value unclaimed.',
    practical_implication: 'Deciding to open at all is a move; practicing the ask is as trainable as any concession pattern.',
    conditions: 'Descriptive findings from specific U.S. workplace samples of the era; social context and role expectations strongly condition initiation behavior.',
    limitations: 'Cross-sectional and situational evidence; gender is a coarse group variable with large within-group variance — individual behavior is not predicted by it.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['Linda Babcock', 'Sara Laschever'],
    year: 2003,
    publication: 'Princeton University Press (book)',
    doi_url: null,
    citation_text: 'Babcock, L., & Laschever, S. (2003). Women Don\'t Ask: Negotiation and the gender divide. Princeton University Press.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-mnookin-beyond-winning',
    title: 'Beyond Winning: Negotiating to create value in deals and disputes',
    summary:
      'Argues the central tension of negotiation is between creating and claiming value, and that empathy (understanding the other side) and assertiveness (pursuing your own) must be combined.',
    ontology_tags: ['VALUE_CREATION', 'VALUE_CAPTURE'],
    claim: 'A widely used negotiation framework recommends combining empathy for the other side\'s constraints with assertiveness about your own — the tension between creating and claiming runs through every negotiation.',
    practical_implication: 'Track both dimensions during a match: how much value is being created, and how much of it you are positioned to claim.',
    conditions: 'The tension is present whenever value creation and claiming interact — most multi-issue and repeated settings.',
    limitations: 'Practitioner-analytic framework; empathy/assertiveness measurement is not standardized.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['Robert H. Mnookin', 'Scott R. Peppet', 'Andrew S. Tulumello'],
    year: 2000,
    publication: 'Harvard University Press (book)',
    doi_url: null,
    citation_text: 'Mnookin, R. H., Peppet, S. R., & Tulumello, A. S. (2000). Beyond Winning: Negotiating to create value in deals and disputes. Harvard University Press.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-cialdini-influence',
    title: 'Influence: The Psychology of Persuasion',
    summary:
      'Catalog of persuasion principles — reciprocity, commitment and consistency, scarcity, authority, liking — with negotiation applications.',
    ontology_tags: ['RECIPROCITY', 'FRAMING', 'CREDIBILITY'],
    claim: 'A widely used negotiation framework recommends recognizing six persuasion principles (reciprocity, commitment/consistency, social proof, authority, liking, scarcity) as levers that operate in negotiation influence.',
    practical_implication: 'Influence operates even when nobody argues: a small concession can trigger a reciprocity norm that shapes the next round.',
    conditions: 'Principles operate on fast, automatic processing; deliberate evaluation weakens their effect.',
    limitations: 'Practitioner synthesis of psychology research; individual studies behind each principle vary in replication status.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['Robert B. Cialdini'],
    year: 1984,
    publication: 'HarperCollins (book)',
    doi_url: null,
    citation_text: 'Cialdini, R. B. (1984). Influence: The Psychology of Persuasion. HarperCollins.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
  {
    id: 'kb-shell-bargaining-advantages',
    title: 'Bargaining for Advantage: Negotiation strategies for reasonable people',
    summary:
      'Practitioner framework organized around information, time, and power as the three levers of bargaining advantage, with preparation habits for each.',
    ontology_tags: ['PLANNING', 'INFORMATION_GATHERING', 'DEADLINES'],
    claim: 'A widely used negotiation framework recommends preparation across three levers: information, time, and power — each shapes the bargaining range and its use.',
    practical_implication: 'Before a match, prepare all three: what you know, what you can learn, and when the clock works for or against you.',
    conditions: 'The three-lever model is a preparation heuristic, not a predictive theory.',
    limitations: 'Practitioner framework without direct empirical validation as a package.',
    evidence_level: 'C',
    source_type: 'BIBLIOGRAPHIC_REFERENCE',
    authors: ['G. Richard Shell'],
    year: 1999,
    publication: 'Penguin Books (book)',
    doi_url: null,
    citation_text: 'Shell, G. R. (1999). Bargaining for Advantage: Negotiation strategies for reasonable people. Penguin Books.',
    license_access: { license: null, access: 'PUBLISHED_BOOK' },
    review_status: 'DRAFT',
    reviewed_by: null,
    created_at: SEED_CREATED_AT,
    version: '0.1.0',
  },
];

/** The curated seed knowledge base, validated at load — any invalid record throws here, not at runtime. */
export function seedKnowledgeRecords(): KnowledgeRecord[] {
  return KNOWLEDGE_SEEDS.map((record) => ({ ...record, authors: [...record.authors], ontology_tags: [...record.ontology_tags] }));
}
